---
# Install packages
- name: Make sure Apache and modules are installed
  apt: name={{ item }}
       state=present
  with_items: "{{ apache_packages }}"

# Template Apache vhost
- name: Set Apache vhost configuration
  template:
    src: templates/vhost.conf.j2
    dest: "{{ apache_conf_path }}/sites-available/vhost.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache


# Set Apache service
- name: Ensure Apache is running and enabled at boot
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
