---
# User
apache_user: www-data

# Service name
apache_service: apache2

# Location of conf
apache_conf_path: /etc/apache2

# Which Apache packages to install
apache_packages:
  - apache2
  - apache2-utils

apache_document_root: /var/www/html
